# Generated by Django 4.2.2 on 2023-06-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
